# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/develop/Data/Xilinx/Workspace/MYC-C7020-4E1D-766-C/project_FT60X_noPS/project_FT60X_noPS.srcs/sources_1/ip/conv_s1n14/conv_s1n14.xci
# IP: The module: 'conv_s1n14' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/develop/Data/Xilinx/Workspace/MYC-C7020-4E1D-766-C/project_FT60X_noPS/project_FT60X_noPS.srcs/sources_1/ip/conv_s1n14/conv_s1n14_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv_s1n14'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/develop/Data/Xilinx/Workspace/MYC-C7020-4E1D-766-C/project_FT60X_noPS/project_FT60X_noPS.srcs/sources_1/ip/conv_s1n14/conv_s1n14.xci
# IP: The module: 'conv_s1n14' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/develop/Data/Xilinx/Workspace/MYC-C7020-4E1D-766-C/project_FT60X_noPS/project_FT60X_noPS.srcs/sources_1/ip/conv_s1n14/conv_s1n14_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv_s1n14'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
