# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/develop/Data/Xilinx/Workspace/MYC-C7020-4E1D-766-C/project_FT60X/project_FT60X.srcs/sources_1/bd/design_ps/ip/design_ps_processing_system7_0_0/design_ps_processing_system7_0_0.xci
# IP: The module: 'design_ps_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/develop/Data/Xilinx/Workspace/MYC-C7020-4E1D-766-C/project_FT60X/project_FT60X.srcs/sources_1/bd/design_ps/ip/design_ps_processing_system7_0_0/design_ps_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ps_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/develop/Data/Xilinx/Workspace/MYC-C7020-4E1D-766-C/project_FT60X/project_FT60X.srcs/sources_1/bd/design_ps/ip/design_ps_processing_system7_0_0/design_ps_processing_system7_0_0.xci
# IP: The module: 'design_ps_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/develop/Data/Xilinx/Workspace/MYC-C7020-4E1D-766-C/project_FT60X/project_FT60X.srcs/sources_1/bd/design_ps/ip/design_ps_processing_system7_0_0/design_ps_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ps_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
