# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/MYB-C7Z0x0.xdc

# Block Designs: bd/design_ps/design_ps.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps || ORIG_REF_NAME==design_ps} -quiet] -quiet

# IP: bd/design_ps/ip/design_ps_processing_system7_0_0/design_ps_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_processing_system7_0_0 || ORIG_REF_NAME==design_ps_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_ps/ip/design_ps_xlconstant_0_0/design_ps_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_xlconstant_0_0 || ORIG_REF_NAME==design_ps_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_ps/ip/design_ps_clockctrl_0_1/design_ps_clockctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_clockctrl_0_1 || ORIG_REF_NAME==design_ps_clockctrl_0_1} -quiet] -quiet

# IP: bd/design_ps/ip/design_ps_xbar_0/design_ps_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_xbar_0 || ORIG_REF_NAME==design_ps_xbar_0} -quiet] -quiet

# IP: bd/design_ps/ip/design_ps_ps7_0_axi_periph_0/design_ps_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_ps_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_ps/ip/design_ps_rst_ps7_0_100M_0/design_ps_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_ps_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_ps/ip/design_ps_FT60X_AXI_0_0/design_ps_FT60X_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_FT60X_AXI_0_0 || ORIG_REF_NAME==design_ps_FT60X_AXI_0_0} -quiet] -quiet

# IP: bd/design_ps/ip/design_ps_auto_pc_0/design_ps_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_auto_pc_0 || ORIG_REF_NAME==design_ps_auto_pc_0} -quiet] -quiet

# XDC: bd/design_ps/design_ps_ooc.xdc
